
ruta.excel=D://OneDrive//Escritorio//Contactos.xlsx

//web.url=https://www.doctorsim.com/en-us/co/topup-phone/

web.url=https://www.doctorsim.com/ec-es/recargar-celular/

proton.vpn=C://Program Files//Proton//VPN//ProtonVPN.Launcher.exe