
ruta.excel=D://OneDrive//Escritorio//Contactos.xlsx

proton.vpn=C://Program Files//Proton//VPN//ProtonVPN.Launcher.exe

web.url=https://www.rebtel.com/es/#{%22country%22:%22CO%22,%22currency%22:%22USD%22}

//web.url=https://www.rebtel.com/es/#{%22country%22:%22EC%22,%22currency%22:%22USD%22}
